# Generated by Django 5.2.1 on 2025-07-23 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='In Progress', max_length=50),
        ),
    ]
