# Generated by Django 5.2.3 on 2025-06-17 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("record_cabinet", "Record Cabinet"),
                    ("dining_table", "Dining Table"),
                    ("coffee_table", "Coffee Table"),
                ],
                default="None",
                max_length=100,
            ),
        ),
    ]
