# Generated by Django 5.2.3 on 2025-06-17 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
