# Generated by Django 5.2.3 on 2025-06-23 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_variation_variationoption_delete_productvariant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="variationoption",
            name="variation",
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wood_type", models.CharField(max_length=100)),
                ("size", models.CharField(max_length=100)),
                (
                    "price_modifier",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Variation",
        ),
        migrations.DeleteModel(
            name="VariationOption",
        ),
    ]
