# Generated by Django 5.2.3 on 2025-06-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_remove_variationoption_variation_productvariant_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
        migrations.AddField(
            model_name="product",
            name="main_image",
            field=models.ImageField(blank=True, upload_to="main_images/"),
        ),
    ]
